from utils import *
from mqt.qcec import verify, verify_compilation
from qiskit_ibm_runtime.fake_provider import FakeAthensV2
from qiskit.transpiler import generate_preset_pass_manager

from qiskit.transpiler import TranspileLayout

def make_transpile_layout_from_property_set(in_qc, out_qc, property_set):
    initial_layout = property_set.get("layout")
    final_layout = property_set.get("final_layout")

    # original input qubit -> original position
    input_qubit_mapping = {q: i for i, q in enumerate(in_qc.qubits)}

    return TranspileLayout(
        initial_layout=initial_layout,
        input_qubit_mapping=input_qubit_mapping,
        final_layout=final_layout,
        _input_qubit_count=len(in_qc.qubits),
        _output_qubit_list=out_qc.qubits,
    )
# 1. Start with the initial circuit as a QASM string
initial_qc_qasm = initialize_circuit(DJCircuitInitialization, 5)

# 2. To verify correctly, we should compile native Qiskit objects 
# so we don't lose the _layout attribute generated by the transpiler.
initial_qc = loads(initial_qc_qasm, custom_instructions=LEGACY_CUSTOM_INSTRUCTIONS)

# We remove measurements if we want to test pure unitary equivalence
# initial_qc.remove_final_measurements(inplace=True)

backend = FakeAthensV2()
pm = generate_preset_pass_manager(optimization_level=3, backend=backend, seed_transpiler=0)
final_qc = pm.run(initial_qc)
transpile_layout = make_transpile_layout_from_property_set(initial_qc, final_qc, pm.property_set)
print("Checking Layout:", final_qc._layout == pm.property_set["layout"])
print(final_qc._layout)
print(transpile_layout)

# 3. Verification succeeds because final_qc has the `_layout` attribute!
print("Verification BEFORE dumps/loads (retains _layout):")
print(verify_compilation(initial_qc, final_qc, check_partial_equivalence=True).equivalence)

# 4. If you MUST use the string-based pipeline (qiskit_compile):
print("\n--- Why dumps/loads breaks verification ---")
final_qc_str, _ = qiskit_compile(dumps(initial_qc), 3, FakeAthensV2())
final_qc_loaded = loads(final_qc_str, custom_instructions=LEGACY_CUSTOM_INSTRUCTIONS)

# Since `loads()` creates a fresh QuantumCircuit, it has NO _layout.
# QCEC assumes a 1:1 hardware mapping which is wrong, causing it to fail.
print("Does loaded QASM have layout?", hasattr(final_qc_loaded, "_layout"))

# If we manually restore the layout from the transpiler:
final_qc_loaded._layout = transpile_layout#final_qc._layout

print("\nVerification AFTER dumps/loads with _layout manually restored:")
print(verify_compilation(initial_qc, final_qc_loaded, check_partial_equivalence=True).equivalence)

# 5. Using QLego's pipeline directly preserves layout via metadata:
print("\n--- Why QLego Pipeline fixes this ---")
from qlego_qiskit.adapter.backend import QiskitBackend
from qlego.qpass import QPipeline, QPassContext
from qlego_qiskit.adapter.passes import PresetPasses
from qlego_mqt_verification.adapter.passes import MQTVerification

# Create the end to end pipeline: Compilation -> Verification
backend_json = QiskitBackend.from_qiskit(FakeAthensV2()).to_json()
pipeline = QPipeline([
    PresetPasses(optimization_level=3),
    MQTVerification()
])
# Context initialized with the QASM string and the initial_qasm metadata needed by MQTVerification
ctx = QPassContext(qasm=initial_qc_qasm, hardware=backend_json, metadata={"initial_qasm": initial_qc_qasm})
ctx = pipeline.run("", ctx)

print("Verification AFTER QLego pipeline (transports layout transparently via metadata):")
print("exact_equivalence:", ctx.metadata.get("exact_equivalence"))
print("partial_equivalence:", ctx.metadata.get("partial_equivalence"))
print("\n--- Let's look at the generated layout metadata ---")
print(ctx.metadata.get("layout"))
